spring:
  datasource:
    url: jdbc:mysql://localhost:3307/coinapo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
          non_contextual_creation: true

coinapocalypse:
  coins:
    count: 0
    maximum: -1

  meteors:
    count: 5
    speed-start: 1.0
    speed-max: 1.5

  player:
    lives: 3
    jump-height: 32.0
    speed: 1.0
