spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/coinapocalypse
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
          non_contextual_creation: true